
import React, { useState, useRef } from 'react';
import { RoadmapResult, ResourceLink, Certification } from '../types';
import { fetchLiveResources } from '../services/geminiService';
import { LOGO } from '../constants';

interface OutputDisplayProps {
  data: RoadmapResult;
  onReset: () => void;
}

declare global {
  interface Window {
    html2pdf: any;
  }
}

export const OutputDisplay: React.FC<OutputDisplayProps> = ({ data, onReset }) => {
  const [videos, setVideos] = useState<ResourceLink[]>([]);
  const [blogs, setBlogs] = useState<ResourceLink[]>([]);
  const [certs, setCerts] = useState<Certification[]>([]);
  const [loadingType, setLoadingType] = useState<'video' | 'blog' | 'certification' | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = async () => {
    if (!reportRef.current || !window.html2pdf) {
      alert("PDF library not ready. Please try again in a moment.");
      return;
    }
    
    setIsExporting(true);
    
    const element = reportRef.current;
    const opt = {
      margin: 10,
      filename: `Botbrained_Learn_${data.title.replace(/\s+/g, '_')}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 2, 
        useCORS: true,
        letterRendering: true,
        backgroundColor: '#ffffff'
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'], before: '.page-break-before' }
    };

    try {
      element.classList.add('pdf-mode');
      await window.html2pdf().set(opt).from(element).save();
      element.classList.remove('pdf-mode');
    } catch (err) {
      console.error('PDF Generation failed:', err);
      alert('PDF generation failed. Using basic print fallback...');
      window.print();
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownloadMarkdown = () => {
    const content = `
# ${data.title}
${data.summary}

## 📚 Syllabus
${data.syllabus.map(m => `### ${m.title}\n${m.description}\n- ${m.lessons.join('\n- ')}`).join('\n\n')}

## 🛠️ AI Mastery Stack
- ${data.tools.join('\n- ')}

## 📽️ Presentation Plan (13 Slides)
${data.presentationPlan.map(s => `Slide ${s.slideNumber}: ${s.title}\nTool: ${s.recommendedTool}\n${s.content}`).join('\n\n')}

## 📣 Marketing Strategy
${data.marketingStrategy.adSets.map(a => `### ${a.positioningStatement}\n- Hook: ${a.staticImages[0]?.hook}\n- Video: ${a.videoIdeas[0]?.title}`).join('\n\n')}

Generated by Botbrained Learn - 2026 AI Roadmap Architect
    `;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.title.replace(/\s+/g, '_')}_Roadmap.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleFetchResources = async (type: 'video' | 'blog' | 'certification') => {
    setLoadingType(type);
    try {
      const results = await fetchLiveResources(type, {
        title: data.title,
        vertical: data.originalSelections?.vertical || "Generic AI",
        level: data.originalSelections?.level || "Beginner",
        persona: data.originalSelections?.persona || "Professional"
      });
      
      if (type === 'video') setVideos(results.map(r => ({ title: r.title || r.name || "Untitled Video", url: r.url, type: 'video' })));
      else if (type === 'blog') setBlogs(results.map(r => ({ title: r.title || r.name || "Untitled Article", url: r.url, type: 'blog' })));
      else if (type === 'certification') setCerts(results.map(r => ({ name: r.name || r.title || "Unknown Certificate", provider: r.provider || "Trusted Provider", url: r.url })));
    } catch (error) {
      console.error(`Failed to fetch ${type}:`, error);
      alert(`The AI couldn't find fresh ${type} links right now. Give it a second and try again!`);
    } finally {
      setLoadingType(null);
    }
  };

  const syllabus = data.syllabus || [];
  const adSets = data.marketingStrategy?.adSets || [];
  const tools = data.tools || [];
  const readingMaterials = data.readingMaterials || [];
  const presentationPlan = data.presentationPlan || [];

  return (
    <div className="max-w-6xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Header Actions - Hidden in PDF/Print */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 print:hidden">
        <div className="flex-1">
          <div className="inline-block px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-black uppercase tracking-tighter rounded-md mb-2">
            Generated Roadmap
          </div>
          <h2 className="text-4xl md:text-5xl font-black text-white mb-2 leading-tight">
            {data.title || "Your AI Roadmap"}
          </h2>
          <p className="text-slate-400 text-lg max-w-2xl leading-relaxed">{data.summary}</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <button 
            onClick={handleDownloadPDF} 
            disabled={isExporting}
            className="px-5 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white hover:opacity-90 transition-all shadow-lg shadow-indigo-600/20 flex items-center gap-2 font-bold text-sm disabled:opacity-50"
          >
            {isExporting ? (
              <span className="flex items-center gap-2">
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Processing...
              </span>
            ) : (
              <span>📥 Download Full PDF</span>
            )}
          </button>
          <button onClick={handleDownloadMarkdown} className="px-5 py-3 rounded-xl bg-white/10 text-white hover:bg-white/20 transition-all flex items-center gap-2 font-bold text-sm">
            <span>💾</span> .md
          </button>
          <button onClick={onReset} className="px-5 py-3 rounded-xl bg-white/5 border border-white/10 text-slate-400 hover:text-white hover:bg-white/10 transition-colors font-bold text-sm">
            Reset
          </button>
        </div>
      </div>

      {/* The Report Body */}
      <div ref={reportRef} className="bg-transparent p-1">
        {/* PDF Header - Visible only in PDF/Print */}
        <div className="hidden pdf-mode:block print:block mb-12 border-b border-slate-200 pb-8">
           <div className="flex items-center gap-3 mb-6">
             <div className="p-3 bg-indigo-600 rounded-xl text-white">
                {LOGO}
             </div>
             <span className="text-3xl font-black text-slate-900 tracking-tighter uppercase italic">botbrained learn</span>
           </div>
           <h1 className="text-5xl font-black text-slate-900 mb-4">{data.title}</h1>
           <p className="text-2xl text-indigo-600 font-bold mb-4">Strategic Course & Implementation Roadmap</p>
           <p className="text-lg text-slate-600 leading-relaxed max-w-3xl">{data.summary}</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-16">
            
            {/* 1. Presentation Plan */}
            <section className="space-y-6">
              <h3 className="text-2xl font-black text-white flex items-center gap-3 print:text-slate-900 pdf-mode:text-slate-900">
                <span className="p-2 bg-blue-500 rounded-lg text-sm print:hidden pdf-mode:hidden">📽️</span> 1. Presentation Strategy
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {presentationPlan.map((slide, i) => (
                  <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-5 flex flex-col page-break-inside-avoid print:bg-slate-50 print:border-slate-200 pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                    <div className="flex justify-between items-start mb-3">
                      <span className="px-2 py-1 bg-blue-600 text-[10px] font-black rounded uppercase text-white">Slide {slide.slideNumber}</span>
                      <span className="text-[10px] font-bold text-blue-600 uppercase tracking-wider">{slide.recommendedTool}</span>
                    </div>
                    <h4 className="text-white font-bold mb-2 print:text-slate-900 pdf-mode:text-slate-900 text-sm">{slide.title}</h4>
                    <p className="text-xs text-slate-400 mb-4 leading-relaxed flex-grow print:text-slate-600 pdf-mode:text-slate-600">{slide.content}</p>
                    <div className="pt-3 border-t border-white/5 mt-auto print:border-slate-200 pdf-mode:border-slate-200">
                      <p className="text-[10px] text-slate-500 italic">
                        <strong className="text-blue-600 not-italic uppercase mr-1">Tool Note:</strong> {slide.toolExplanation}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* 2. Syllabus */}
            <section className="space-y-6 page-break-before">
              <h3 className="text-2xl font-black text-white flex items-center gap-3 print:text-slate-900 pdf-mode:text-slate-900">
                <span className="p-2 bg-indigo-500 rounded-lg text-sm print:hidden pdf-mode:hidden">📚</span> 2. The Curriculum
              </h3>
              <div className="space-y-4">
                {syllabus.map((module, i) => (
                  <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-6 page-break-inside-avoid print:bg-slate-50 print:border-slate-200 pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                    <h4 className="text-xl font-bold text-indigo-400 mb-2 print:text-indigo-700 pdf-mode:text-indigo-700">{module.title}</h4>
                    <p className="text-slate-300 mb-4 text-sm leading-relaxed print:text-slate-700 pdf-mode:text-slate-700">{module.description}</p>
                    <ul className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-2">
                      {module.lessons?.map((lesson, j) => (
                        <li key={j} className="flex items-start gap-2 text-slate-400 text-xs print:text-slate-600 pdf-mode:text-slate-600">
                          <span className="text-indigo-500 font-bold">•</span>
                          {lesson}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </section>

            {/* 3. Technology Stack - MOVED TO MAIN FLOW FOR PDF */}
            <section className="space-y-6 page-break-before hidden pdf-mode:block print:block">
              <h3 className="text-2xl font-black text-slate-900 flex items-center gap-3">
                 3. AI Mastery Stack
              </h3>
              <div className="grid grid-cols-2 gap-4">
                {tools.map((tool, i) => (
                  <div key={i} className="px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-800">
                    {tool}
                  </div>
                ))}
              </div>
            </section>

            {/* 4. Marketing Strategy */}
            <section className="space-y-8 page-break-before">
               <h3 className="text-2xl font-black text-white flex items-center gap-3 print:text-slate-900 pdf-mode:text-slate-900">
                <span className="p-2 bg-purple-500 rounded-lg text-sm print:hidden pdf-mode:hidden">📣</span> 4. Marketing Campaign Suite
              </h3>
              <div className="space-y-10">
                {adSets.map((set, i) => (
                  <div key={i} className="space-y-6 bg-white/5 p-8 rounded-3xl border border-white/5 shadow-inner page-break-inside-avoid print:bg-slate-50 print:border-slate-200 pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                    <div className="space-y-2">
                      <span className="text-xs font-black text-purple-400 uppercase tracking-widest">Angle {i+1}</span>
                      <h4 className="text-2xl font-black text-white print:text-slate-900 pdf-mode:text-slate-900 leading-tight">{set.positioningStatement}</h4>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="space-y-4">
                        <h5 className="text-xs font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2 print:border-slate-200 pdf-mode:border-slate-200">Static Content</h5>
                        {set.staticImages?.slice(0, 1).map((img, j) => (
                          <div key={j} className="p-4 bg-white/5 rounded-xl border border-white/5 print:bg-white pdf-mode:bg-white">
                            <p className="text-indigo-600 font-bold mb-1 italic text-sm">"{img.hook}"</p>
                            <p className="text-[10px] text-slate-500 leading-relaxed">{img.visual}</p>
                          </div>
                        ))}
                      </div>
                      <div className="space-y-4">
                        <h5 className="text-xs font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2 print:border-slate-200 pdf-mode:border-slate-200">Video Script Idea</h5>
                        {set.videoIdeas?.slice(0, 1).map((vid, j) => (
                          <div key={j} className="p-4 bg-white/5 rounded-xl border border-white/5 print:bg-white pdf-mode:bg-white">
                            <p className="text-slate-900 font-bold text-xs mb-1 underline decoration-indigo-500 underline-offset-4">{vid.title}</p>
                            <p className="text-[10px] text-slate-600 leading-relaxed italic">{vid.scriptHook}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>

            {/* 5. Discovery & Certs - MOVED TO MAIN FLOW FOR PDF */}
            <section className="space-y-8 page-break-before hidden pdf-mode:block print:block">
              <h3 className="text-2xl font-black text-slate-900 flex items-center gap-3">
                 5. Certifications & Credentials
              </h3>
              <div className="grid grid-cols-1 gap-4">
                {certs.length > 0 ? certs.map((cert, i) => (
                  <div key={i} className="p-4 bg-slate-50 border border-slate-200 rounded-xl">
                    <p className="font-bold text-slate-900">{cert.name}</p>
                    <p className="text-indigo-600 text-sm">{cert.provider}</p>
                  </div>
                )) : <p className="text-slate-500 italic">No certifications verified during this session.</p>}
              </div>
              
              <h3 className="text-2xl font-black text-slate-900 mt-12 mb-6">6. Curated Readings</h3>
              <div className="space-y-4">
                {readingMaterials.map((book, i) => (
                  <div key={i} className="p-4 bg-slate-50 border border-slate-200 rounded-xl italic text-slate-700">
                    {book}
                  </div>
                ))}
              </div>
            </section>

            {/* Verified Resources - Visible in PDF if fetched during session */}
            {(videos.length > 0 || blogs.length > 0) && (
              <section className="space-y-6 page-break-before">
                <h3 className="text-2xl font-black text-white flex items-center gap-3 print:text-slate-900 pdf-mode:text-slate-900">
                  <span className="p-2 bg-red-500 rounded-lg text-sm print:hidden pdf-mode:hidden">🔍</span> Additional Verified Resources
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {videos.length > 0 && (
                    <div className="bg-white/5 border border-white/10 rounded-2xl p-6 print:bg-slate-50 print:border-slate-200 pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                      <h4 className="text-lg font-black text-red-600 mb-4">YouTube Mastery</h4>
                      <ul className="space-y-2">
                        {videos.map((res, i) => (
                          <li key={i} className="text-xs font-bold text-indigo-700 truncate">{res.title}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {blogs.length > 0 && (
                    <div className="bg-white/5 border border-white/10 rounded-2xl p-6 print:bg-slate-50 print:border-slate-200 pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                      <h4 className="text-lg font-black text-blue-600 mb-4">Case Studies</h4>
                      <ul className="space-y-2">
                        {blogs.map((res, i) => (
                          <li key={i} className="text-xs font-bold text-indigo-700 truncate">{res.title}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </section>
            )}

            {/* Interactive UI Discovery - Hidden in PDF/Print */}
            <section className="space-y-6 print:hidden pdf-mode:hidden">
              <h3 className="text-2xl font-black text-white flex items-center gap-3">
                <span className="p-2 bg-red-500 rounded-lg text-sm">⚡</span> Live Discovery
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-white/5 border border-white/10 rounded-2xl p-6 flex flex-col items-center justify-center min-h-[200px] text-center">
                  <h4 className="text-lg font-black text-red-400 mb-4 flex items-center gap-2">📺 YouTube Tutorials</h4>
                  {videos.length === 0 ? (
                    <button onClick={() => handleFetchResources('video')} disabled={loadingType === 'video'} className="px-6 py-3 bg-red-500/10 border border-red-500/20 text-red-400 rounded-xl font-black text-xs hover:bg-red-500/20 transition-all disabled:opacity-50">
                      {loadingType === 'video' ? 'SCANNING...' : 'FETCH VIDEOS'}
                    </button>
                  ) : (
                    <ul className="w-full space-y-2 text-left">
                      {videos.map((res, i) => (
                        <li key={i} className="text-xs bg-black/40 p-3 rounded-lg border border-white/5"><a href={res.url} target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:text-indigo-300 font-bold block truncate">{res.title}</a></li>
                      ))}
                    </ul>
                  )}
                </div>
                <div className="bg-white/5 border border-white/10 rounded-2xl p-6 flex flex-col items-center justify-center min-h-[200px] text-center">
                  <h4 className="text-lg font-black text-blue-400 mb-4 flex items-center gap-2">✍️ Articles & Cases</h4>
                  {blogs.length === 0 ? (
                    <button onClick={() => handleFetchResources('blog')} disabled={loadingType === 'blog'} className="px-6 py-3 bg-blue-500/10 border border-blue-500/20 text-blue-400 rounded-xl font-black text-xs hover:bg-blue-500/20 transition-all disabled:opacity-50">
                      {loadingType === 'blog' ? 'MINING...' : 'FETCH ARTICLES'}
                    </button>
                  ) : (
                    <ul className="w-full space-y-2 text-left">
                      {blogs.map((res, i) => (
                        <li key={i} className="text-xs bg-black/40 p-3 rounded-lg border border-white/5"><a href={res.url} target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:text-indigo-300 font-bold block truncate">{res.title}</a></li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            </section>
          </div>

          {/* Sidebar - Hidden in PDF/Print because it's re-organized into the main flow */}
          <div className="space-y-8 print:hidden pdf-mode:hidden">
            <div className="bg-indigo-600/10 border border-indigo-500/30 rounded-3xl p-6 shadow-xl">
               <h4 className="text-xs font-black text-indigo-400 uppercase mb-4 tracking-widest italic underline decoration-2 underline-offset-4">🛠️ AI Mastery Stack</h4>
               <ul className="grid grid-cols-1 gap-2">
                 {tools.map((tool, i) => (
                   <li key={i} className="px-4 py-2 bg-white/5 rounded-xl text-xs font-bold text-white border border-white/10 hover:bg-white/10 transition-colors">{tool}</li>
                 ))}
               </ul>
            </div>

            <div className="bg-amber-500/10 border border-amber-500/30 rounded-3xl p-6 shadow-xl">
               <h4 className="text-xs font-black text-amber-500 uppercase mb-4 tracking-widest italic underline decoration-2 underline-offset-4">🏆 Certifications</h4>
               <div className="space-y-4">
                 {certs.length === 0 ? (
                   <div className="text-center p-4">
                      <button onClick={() => handleFetchResources('certification')} disabled={loadingType === 'certification'} className="w-full py-3 bg-amber-500/20 border border-amber-500/30 text-amber-500 text-xs font-black rounded-xl hover:bg-amber-500/30 transition-all disabled:opacity-50">
                        {loadingType === 'certification' ? 'VALIDATING...' : 'FETCH CERTS'}
                      </button>
                   </div>
                 ) : (
                   certs.map((cert, i) => (
                     <div key={i} className="text-xs border-b border-white/5 pb-3 last:border-0">
                        <p className="font-black text-white mb-1">{cert.name}</p>
                        <p className="text-amber-500/80 text-[10px] mb-2">{cert.provider}</p>
                     </div>
                   ))
                 )}
               </div>
            </div>

            <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-3xl p-6 shadow-xl">
               <h4 className="text-xs font-black text-emerald-500 uppercase mb-4 tracking-widest italic underline decoration-2 underline-offset-4">📖 Deep Reading</h4>
               <ul className="space-y-4">
                  {readingMaterials.map((book, i) => (
                    <li key={i} className="text-[11px] text-slate-400 leading-relaxed border-l-2 border-emerald-500/40 pl-3 italic">
                      {book}
                    </li>
                  ))}
               </ul>
            </div>
          </div>
        </div>
        
        {/* PDF Footer */}
        <div className="hidden pdf-mode:block print:block mt-16 pt-8 border-t border-slate-200 text-center text-slate-400 text-sm italic">
           Generated by Botbrained Learn • 2026 AI Roadmap Architect • All Rights Reserved
        </div>
      </div>
    </div>
  );
};
