
import React, { useState, useRef } from 'react';
import { RoadmapResult, ResourceLink, Certification } from '../types.ts';
import { fetchLiveResources } from '../services/geminiService.ts';
import { LOGO } from '../constants.tsx';

interface OutputDisplayProps {
  data: RoadmapResult;
  onReset: () => void;
}

declare global {
  interface Window {
    html2pdf: any;
  }
}

export const OutputDisplay: React.FC<OutputDisplayProps> = ({ data, onReset }) => {
  const [videos, setVideos] = useState<ResourceLink[]>([]);
  const [blogs, setBlogs] = useState<ResourceLink[]>([]);
  const [certs, setCerts] = useState<Certification[]>([]);
  const [loadingType, setLoadingType] = useState<'video' | 'blog' | 'certification' | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = async () => {
    if (!reportRef.current || !window.html2pdf) {
      alert("PDF library not ready. Please try again in a moment.");
      return;
    }
    
    setIsExporting(true);
    
    const element = reportRef.current;
    const opt = {
      margin: 15,
      filename: `Botbrained_Learn_${data.title.replace(/\s+/g, '_')}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 3, // High DPI for crisp text
        useCORS: true,
        letterRendering: true,
        backgroundColor: '#ffffff',
        logging: false
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
      element.classList.add('pdf-mode');
      await window.html2pdf().set(opt).from(element).save();
      element.classList.remove('pdf-mode');
    } catch (err) {
      console.error('PDF Generation failed:', err);
      alert('PDF generation failed. Using basic print fallback...');
      window.print();
    } finally {
      setIsExporting(false);
    }
  };

  const handleDownloadMarkdown = () => {
    const content = `
# ${data.title}
${data.summary}

## 📚 Curriculum
${data.syllabus.map(m => `### ${m.title}\n${m.description}\n- ${m.lessons.join('\n- ')}`).join('\n\n')}

## 🛠️ AI Mastery Stack
- ${data.tools.join('\n- ')}

## 🧠 Topics to Cover
${data.topicsToCover.map(t => `Topic ${t.topicNumber}: ${t.title}\nTool: ${t.recommendedTool}\n${t.content}`).join('\n\n')}

Generated by Botbrained Learn - 2026 AI Roadmap Architect
    `;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.title.replace(/\s+/g, '_')}_Roadmap.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleFetchResources = async (type: 'video' | 'blog' | 'certification') => {
    setLoadingType(type);
    try {
      const results = await fetchLiveResources(type, {
        title: data.title,
        vertical: data.originalSelections?.vertical || "Generic AI",
        level: data.originalSelections?.level || "Beginner",
        persona: data.originalSelections?.persona || "Professional"
      });
      
      if (type === 'video') setVideos(results.map(r => ({ title: r.title || r.name || "Untitled Video", url: r.url, type: 'video' })));
      else if (type === 'blog') setBlogs(results.map(r => ({ title: r.title || r.name || "Untitled Article", url: r.url, type: 'blog' })));
      else if (type === 'certification') setCerts(results.map(r => ({ name: r.name || r.title || "Unknown Certificate", provider: r.provider || "Trusted Provider", url: r.url })));
    } catch (error) {
      console.error(`Failed to fetch ${type}:`, error);
    } finally {
      setLoadingType(null);
    }
  };

  const syllabus = data.syllabus || [];
  const adSets = data.marketingStrategy?.adSets || [];
  const tools = data.tools || [];
  const readingMaterials = data.readingMaterials || [];
  const topicsToCover = data.topicsToCover || [];

  return (
    <div className="max-w-6xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
      {/* Interactive Controls */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 print:hidden">
        <div className="flex-1">
          <div className="inline-block px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-black uppercase tracking-tighter rounded-md mb-2">
            AI Generation Complete
          </div>
          <h2 className="text-4xl md:text-5xl font-black text-white mb-2 leading-tight">
            {data.title}
          </h2>
          <p className="text-slate-400 text-lg max-w-2xl leading-relaxed">{data.summary}</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <button 
            onClick={handleDownloadPDF} 
            disabled={isExporting}
            className="px-6 py-4 rounded-2xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white hover:opacity-90 transition-all shadow-lg shadow-indigo-600/20 flex items-center gap-2 font-bold disabled:opacity-50"
          >
            {isExporting ? 'Generating PDF...' : '📥 Download PDF'}
          </button>
          <button onClick={handleDownloadMarkdown} className="px-6 py-4 rounded-2xl bg-white/10 text-white hover:bg-white/20 transition-all font-bold">
            .md
          </button>
          <button onClick={onReset} className="px-6 py-4 rounded-2xl bg-white/5 border border-white/10 text-slate-400 hover:text-white transition-colors font-bold">
            Reset
          </button>
        </div>
      </div>

      {/* The Report Body */}
      <div ref={reportRef} className="bg-transparent p-1">
        {/* PDF Header - Hidden in Web View */}
        <div className="hidden pdf-mode:block print:block mb-12 border-b-4 border-indigo-600 pb-8">
           <div className="flex items-center gap-3 mb-8">
             <div className="p-4 bg-indigo-600 rounded-2xl text-white">
                {LOGO}
             </div>
             <span className="text-4xl font-black text-slate-900 tracking-tighter uppercase italic">botbrained learn</span>
           </div>
           <h1 className="text-6xl font-black text-slate-900 mb-4">{data.title}</h1>
           <p className="text-2xl text-indigo-600 font-bold mb-6">Strategic Implementation Roadmap: 2026 Edition</p>
           <p className="text-xl text-slate-600 leading-relaxed italic">{data.summary}</p>
        </div>

        <div className="space-y-16">
          {/* 1. Topics to Cover */}
          <section className="space-y-8">
            <h3 className="text-3xl font-black text-white flex items-center gap-3 pdf-mode:text-slate-900 print:text-slate-900">
              <span className="p-2 bg-blue-500 rounded-xl text-sm pdf-mode:hidden print:hidden">🧠</span> 1. Core Topics to Cover
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pdf-mode:grid-cols-1 print:grid-cols-1">
              {topicsToCover.map((topic, i) => (
                <div key={i} className="bg-white/5 border border-white/10 rounded-3xl p-8 flex flex-col page-break-inside-avoid pdf-mode:bg-slate-50 pdf-mode:border-slate-200 pdf-mode:mb-8 pdf-mode:rounded-xl pdf-mode:p-10 pdf-mode:shadow-none">
                  <div className="flex justify-between items-start mb-4">
                    <span className="px-3 py-1 bg-blue-600 text-[10px] font-black rounded-lg uppercase text-white">Topic {topic.topicNumber}</span>
                    <span className="text-xs font-black text-blue-500 uppercase tracking-widest">{topic.recommendedTool}</span>
                  </div>
                  <h4 className="text-2xl font-black text-white mb-4 pdf-mode:text-slate-900 print:text-slate-900">{topic.title}</h4>
                  <p className="text-sm text-slate-400 mb-6 leading-relaxed flex-grow pdf-mode:text-slate-700 print:text-slate-700">{topic.content}</p>
                  <div className="pt-4 border-t border-white/5 mt-auto pdf-mode:border-slate-200 print:border-slate-200">
                    <p className="text-xs text-slate-500 italic">
                      <strong className="text-blue-500 not-italic uppercase mr-2 font-black">Architecture Insight:</strong> {topic.toolExplanation}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 2. Syllabus */}
          <section className="space-y-8 page-break-before">
            <h3 className="text-3xl font-black text-white flex items-center gap-3 pdf-mode:text-slate-900 print:text-slate-900">
              <span className="p-2 bg-indigo-500 rounded-xl text-sm pdf-mode:hidden print:hidden">📚</span> 2. The Curriculum Breakdown
            </h3>
            <div className="space-y-6">
              {syllabus.map((module, i) => (
                <div key={i} className="bg-white/5 border border-white/10 rounded-3xl p-8 page-break-inside-avoid pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                  <h4 className="text-2xl font-black text-indigo-400 mb-3 pdf-mode:text-indigo-700 print:text-indigo-700">{module.title}</h4>
                  <p className="text-slate-300 mb-6 text-base leading-relaxed pdf-mode:text-slate-700 print:text-slate-700">{module.description}</p>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {module.lessons?.map((lesson, j) => (
                      <div key={j} className="flex items-start gap-3 text-slate-400 text-sm pdf-mode:text-slate-600">
                        <span className="text-indigo-500 font-black">◈</span>
                        {lesson}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 3. Tech Stack */}
          <section className="space-y-8 page-break-before">
            <h3 className="text-3xl font-black text-white flex items-center gap-3 pdf-mode:text-slate-900 print:text-slate-900">
              <span className="p-2 bg-emerald-500 rounded-xl text-sm pdf-mode:hidden print:hidden">🛠️</span> 3. Essential Tech Stack
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
              {tools.map((tool, i) => (
                <div key={i} className="px-6 py-4 bg-white/5 border border-white/10 rounded-2xl text-sm font-black text-white text-center pdf-mode:bg-slate-50 pdf-mode:text-slate-900 pdf-mode:border-slate-200">
                  {tool}
                </div>
              ))}
            </div>
          </section>

          {/* 4. Marketing Strategy */}
          <section className="space-y-12 page-break-before">
             <h3 className="text-3xl font-black text-white flex items-center gap-3 pdf-mode:text-slate-900 print:text-slate-900">
              <span className="p-2 bg-purple-500 rounded-xl text-sm pdf-mode:hidden print:hidden">📣</span> 4. Growth & Positioning
            </h3>
            <div className="space-y-12">
              {adSets.map((set, i) => (
                <div key={i} className="space-y-8 bg-white/5 p-10 rounded-3xl border border-white/5 page-break-inside-avoid pdf-mode:bg-slate-50 pdf-mode:border-slate-200">
                  <div className="space-y-2">
                    <span className="text-xs font-black text-purple-400 uppercase tracking-[0.3em]">Campaign Angle {i+1}</span>
                    <h4 className="text-3xl font-black text-white pdf-mode:text-slate-900 print:text-slate-900 leading-tight">{set.positioningStatement}</h4>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                    <div className="space-y-6">
                      <h5 className="text-xs font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2 pdf-mode:border-slate-300">High-Impact Static</h5>
                      {set.staticImages?.slice(0, 1).map((img, j) => (
                        <div key={j} className="p-6 bg-white/5 rounded-2xl border border-white/5 pdf-mode:bg-white pdf-mode:border-slate-200">
                          <p className="text-indigo-600 font-black mb-3 italic text-lg">"{img.hook}"</p>
                          <p className="text-xs text-slate-500 leading-relaxed">{img.visual}</p>
                        </div>
                      ))}
                    </div>
                    <div className="space-y-6">
                      <h5 className="text-xs font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2 pdf-mode:border-slate-300">Short-Form Script</h5>
                      {set.videoIdeas?.slice(0, 1).map((vid, j) => (
                        <div key={j} className="p-6 bg-white/5 rounded-2xl border border-white/5 pdf-mode:bg-white pdf-mode:border-slate-200">
                          <p className="text-slate-900 font-black text-sm mb-2 underline decoration-indigo-500 underline-offset-8 decoration-2">{vid.title}</p>
                          <p className="text-xs text-slate-600 leading-relaxed italic">{vid.scriptHook}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* 5. Deep Reading & Outcome */}
          <section className="grid grid-cols-1 md:grid-cols-2 gap-8 page-break-before">
            <div className="space-y-6">
              <h3 className="text-2xl font-black text-white pdf-mode:text-slate-900 print:text-slate-900">📖 Essential Reading</h3>
              <div className="space-y-4">
                {readingMaterials.map((book, i) => (
                  <div key={i} className="p-5 bg-white/5 border border-white/10 rounded-2xl text-slate-400 italic text-sm pdf-mode:bg-slate-50 pdf-mode:text-slate-700 pdf-mode:border-slate-200">
                    {book}
                  </div>
                ))}
              </div>
            </div>
            <div className="space-y-6">
               <h3 className="text-2xl font-black text-white pdf-mode:text-slate-900 print:text-slate-900">🏆 Key Outcomes</h3>
               <div className="space-y-4">
                 {data.outcomes.map((outcome, i) => (
                   <div key={i} className="p-5 bg-indigo-600/10 border border-indigo-500/20 rounded-2xl text-indigo-400 font-bold text-sm pdf-mode:bg-indigo-50 pdf-mode:text-indigo-700 pdf-mode:border-indigo-100">
                     {outcome}
                   </div>
                 ))}
               </div>
            </div>
          </section>
        </div>
        
        {/* PDF Footer */}
        <div className="hidden pdf-mode:block print:block mt-24 pt-12 border-t-2 border-slate-100 text-center text-slate-400 text-xs tracking-widest uppercase">
           Generated by Botbrained Learn AI Architect • 2026 Strategic Planning
        </div>
      </div>

      {/* Discovery Section - Hidden in PDF */}
      <section className="space-y-8 pt-12 border-t border-white/5 print:hidden">
        <h3 className="text-3xl font-black text-white">⚡ Discovery Engine</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <button 
            onClick={() => handleFetchResources('video')} 
            disabled={loadingType === 'video'}
            className="p-8 bg-red-500/10 border border-red-500/20 rounded-3xl text-center hover:bg-red-500/20 transition-all disabled:opacity-50"
          >
            <div className="text-3xl mb-4">📺</div>
            <h4 className="text-red-400 font-black uppercase tracking-widest text-xs">Fetch Tutorials</h4>
          </button>
          <button 
            onClick={() => handleFetchResources('blog')} 
            disabled={loadingType === 'blog'}
            className="p-8 bg-blue-500/10 border border-blue-500/20 rounded-3xl text-center hover:bg-blue-500/20 transition-all disabled:opacity-50"
          >
            <div className="text-3xl mb-4">✍️</div>
            <h4 className="text-blue-400 font-black uppercase tracking-widest text-xs">Case Studies</h4>
          </button>
          <button 
            onClick={() => handleFetchResources('certification')} 
            disabled={loadingType === 'certification'}
            className="p-8 bg-amber-500/10 border border-amber-500/20 rounded-3xl text-center hover:bg-amber-500/20 transition-all disabled:opacity-50"
          >
            <div className="text-3xl mb-4">🏆</div>
            <h4 className="text-amber-500 font-black uppercase tracking-widest text-xs">Verify Certs</h4>
          </button>
        </div>
        
        {/* Resource Results Area */}
        {(videos.length > 0 || blogs.length > 0 || certs.length > 0) && (
          <div className="bg-white/5 border border-white/10 rounded-3xl p-8 space-y-6">
            {videos.length > 0 && (
              <div>
                <h4 className="text-red-400 font-black mb-4">Videos</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {videos.map((v, i) => (
                    <a key={i} href={v.url} target="_blank" rel="noopener noreferrer" className="p-4 bg-black/40 rounded-xl border border-white/5 text-sm hover:border-indigo-500 transition-colors block truncate">{v.title}</a>
                  ))}
                </div>
              </div>
            )}
            {blogs.length > 0 && (
              <div className="pt-6 border-t border-white/5">
                <h4 className="text-blue-400 font-black mb-4">Articles</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {blogs.map((b, i) => (
                    <a key={i} href={b.url} target="_blank" rel="noopener noreferrer" className="p-4 bg-black/40 rounded-xl border border-white/5 text-sm hover:border-indigo-500 transition-colors block truncate">{b.title}</a>
                  ))}
                </div>
              </div>
            )}
            {certs.length > 0 && (
              <div className="pt-6 border-t border-white/5">
                <h4 className="text-amber-500 font-black mb-4">Credentials</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {certs.map((c, i) => (
                    <a key={i} href={c.url} target="_blank" rel="noopener noreferrer" className="p-4 bg-black/40 rounded-xl border border-white/5 text-sm hover:border-indigo-500 transition-colors block">
                      <p className="font-bold">{c.name}</p>
                      <p className="text-xs text-slate-500">{c.provider}</p>
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </section>
    </div>
  );
};
